apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: capstone-gbc
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: public.ecr.aws/w3w7t4h3/capstone-gbc-backend:latest
          env:
            - name: MONGODB_URI
              value: "mongodb+srv://akul:akul@cluster0.wb1vjpj.mongodb.net/"
          ports:
            - containerPort: 3500
---
apiVersion: v1
kind: Service
metadata:
  namespace: capstone-gbc
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3500
      targetPort: 3500
